GET http://localhost:8000/admin

###
POST http://localhost:8000/registeradmin
Content-Type: application/json

{
    "username":"Adminfiling",
    "password":"filing2022*",
    "confPassword":"filing2022*"
}

###
POST http://localhost:8000/loginadmin
Content-Type: application/json

{
    "username":"Adminfiling",
    "password":"filing2022*",
}